/**
 * @file font.h
 * @brief The shape of a generated bitmap font.
 *
 * The two fonts in this directory are generated by tools/make_font.py and both
 * have this layout. Keeping the shape here rather than in each generated file
 * means the drawing code includes one definition, not two that have to agree.
 *
 * All of this is temporary. LVGL arrives in phase 4 with its own text
 * rendering, and the only part of the panel driver that outlives it is the
 * flush.
 */
#ifndef UI_FONT_H
#define UI_FONT_H

#include <stdint.h>

/** Where one glyph's pixels start, and how wide it is. */
typedef struct {
  uint16_t offset; /**< Byte offset into the font's pixel data. */
  uint8_t width;   /**< Width in pixels. Rows are padded to whole bytes. */
} FontGlyph;

/** A bitmap font: the pixels, the index, and how tall a line is. */
typedef struct {
  const uint8_t *bits;     /**< Every glyph's pixels, one after another. */
  const FontGlyph *glyphs; /**< One entry per character, in order. */
  uint8_t height;          /**< Line height in pixels. */
  uint8_t first;           /**< First character, or 0 for a digits font. */
  uint8_t last;            /**< Last character, or 0 for a digits font. */
} Font;

#endif /* UI_FONT_H */
