/*
 * The type scale, as LVGL fonts.
 *
 * Roboto Condensed at eight sizes and two weights, generated by
 * `tools/make_lvgl_font.py`. Every one is subset to the glyphs that size shows,
 * which is what keeps the whole scale near a hundred kilobytes instead of over
 * a megabyte.
 *
 * Names say what a size is for rather than how big it is. A screen asking for
 * `roboto_label` keeps saying the right thing if the scale is retuned, where
 * one asking for a 13 pixel font does not.
 *
 * **The numeric face carries digits, a point, a plus, a minus, a space and a
 * colon, and nothing else.** Printing a letter in it draws nothing at all. It
 * is for the frequency and for a full screen setting value, and the fifteen
 * glyphs are the reason the 52 pixel face fits at all. Neither sign is
 * optional: a UTC offset such as -05:00 or +05:30 is a setting value shown on
 * this face, and a table missing either draws nothing where the sign
 * belongs.
 */
#ifndef UI_FONTS_H
#define UI_FONTS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

/* 52px, SemiBold. The frequency, a setting value being changed and the
 * firmware write percentage. Digits, point, plus, minus, space and colon
 * only. */
LV_FONT_DECLARE(roboto_freq)

/* 26px, SemiBold. A setting value being changed that is a word, and the
 * station name on RDS page 1. */
LV_FONT_DECLARE(roboto_name)

/* 24px, Medium. The signal level on the frequency panel, the PI on the DX page
 * and on RDS page 1, and the dwell seconds left on the Scanner page. */
LV_FONT_DECLARE(roboto_value)

/* 21px, Medium. The station name, the tuner on the boot screen, a message
 * title and the unit beside a big value. Carries the ellipsis. */
LV_FONT_DECLARE(roboto_menu)

/* 20px, SemiBold. The band name and every screen title. */
LV_FONT_DECLARE(roboto_title)

/* 17px, Medium. Radio text, the frequency unit, a menu row and a message
 * detail. Carries the ellipsis. */
LV_FONT_DECLARE(roboto_text)

/* 15px, Medium. The clock, the date, the memory slot and every tile and row
 * value. Carries the ellipsis. */
LV_FONT_DECLARE(roboto_small)

/* 13px, Medium. A label, the signal unit, a hint and a scale marking.
 * Carries the micro sign, the middle dot, the ellipsis and the times sign. */
LV_FONT_DECLARE(roboto_label)

/*
 * The status symbols, out of Material Symbols Outlined rather than Roboto.
 *
 * Twenty three glyphs: the network symbol's six, which are joined with its
 * two partial strengths, trying to join, serving its own access point and
 * none of those, the tick and the cross the boot screen and the menus mark
 * with, the chevron on a menu row that opens a list, the four marks on the DX
 * page's PI tile, the NEW badge and the empty inbox of the DX Catches page,
 * the badge again on the update offer's title, the run and stopped marks of
 * the DX scanner, the four on the tiles of RDS
 * page 1 and the stereo mark in its header, and the person in bed that says
 * auto off is on, which alone is cut from the filled style.
 *
 * They live in their own face because they come from a different typeface,
 * and they are 16px, which is the smallest Material Symbols stays legible at
 * and close enough to the 15 of the words beside them that the row reads as
 * one line. The battery is drawn rather than set, because a glyph can show a
 * battery or a number and not both.
 *
 * Apache 2.0, the same as Roboto, so they ship in this GPLv3 project.
 * `ICON_CODEPOINTS` in tools/make_lvgl_font.py is the list and says what each
 * one is for. Anything that is an acronym rather than a thing, RDS and AF and
 * TP and TA, stays as text.
 */
LV_FONT_DECLARE(roboto_icons)

#define ICON_WIFI "\xEE\x98\xBE"         /* U+E63E wifi */
#define ICON_WIFI_2_BAR "\xEE\x93\x99"   /* U+E4D9 wifi_2_bar */
#define ICON_WIFI_1_BAR "\xEE\x93\x8A"   /* U+E4CA wifi_1_bar */
#define ICON_WIFI_FIND "\xEE\xAC\xB1"    /* U+EB31 wifi_find */
#define ICON_WIFI_AP "\xEE\x87\xA2"      /* U+E1E2 wifi_tethering */
#define ICON_WIFI_OFF "\xEE\x99\x88"     /* U+E648 wifi_off */
#define ICON_TICK "\xEE\x99\xA8"         /* U+E668 check */
#define ICON_CROSS "\xEE\x97\x8D"        /* U+E5CD close */
#define ICON_CHEVRON "\xEE\x97\x8C"      /* U+E5CC chevron_right */
#define ICON_CHEVRON_LEFT "\xEE\x97\x8B" /* U+E5CB chevron_left */
#define ICON_BACKSPACE "\xEE\x85\x8A"    /* U+E14A backspace */
#define ICON_MINUS "\xEE\x85\x9B"        /* U+E15B remove */
#define ICON_PLUS "\xEE\x85\x85"         /* U+E145 add */
#define ICON_MENU "\xEE\xAE\xA8"         /* U+EBA8 density_small */
#define ICON_CHECK_CIRCLE "\xEE\xA1\xAC" /* U+E86C check_circle */
#define ICON_HELP "\xEE\xA2\x87"         /* U+E887 help */
#define ICON_SCHEDULE "\xEE\xA2\xB5"     /* U+E8B5 schedule */
#define ICON_BLOCK "\xEE\x85\x8B"        /* U+E14B block */
#define ICON_NEW "\xEE\x80\xB1"          /* U+E031 new_releases */
#define ICON_INBOX "\xEE\x85\x96"        /* U+E156 inbox */
#define ICON_PLAY "\xEE\x80\xB7"         /* U+E037 play_arrow */
#define ICON_PAUSE "\xEE\x80\xB4"        /* U+E034 pause */
#define ICON_TRAFFIC "\xEE\x95\xA5"      /* U+E565 traffic */
#define ICON_CAMPAIGN "\xEE\xBD\x89"     /* U+EF49 campaign */
#define ICON_MUSIC "\xEE\x90\x85"        /* U+E405 music_note */
#define ICON_SPEECH "\xEE\xA4\x9F"       /* U+E91F record_voice_over */
#define ICON_COMPUTER "\xEE\x8C\x8A"     /* U+E30A computer */
#define ICON_EQ "\xEE\x86\xB8"           /* U+E1B8 graphic_eq */
#define ICON_SLEEP "\xEE\x94\xBA"        /* U+E53A hotel, filled */

#ifdef __cplusplus
}
#endif

#endif /* UI_FONTS_H */
