"""Turn the AGC captures into a header the native tests can replay.

The tests have to run anywhere, including on the CI machine, so they cannot
open a file out of the working directory. Generating a header keeps the test
hermetic and keeps the real readings as the thing being tested.

    python3 tools/make_agc.py test/test_agc/captures.h test/fixtures/agc/*.log

The AGC's noise limit is set from the squelch capture rather than from these,
because that is the only capture here holding stations, the channel beside a
strong station and an empty channel all sampled the same way. The station
readings from it are emitted alongside, so the test that the limit rejects no
real station has the real numbers to check against.

Same idea as tools/make_sweep.py and tools/make_squelch.py. Rerun it when a
capture is added or retaken, run clang-format over the result, and commit it.
The format gate covers generated headers like any other file.

Each line of a capture is one printed sample, not one AGC update: the
prototype ran ten times a second and printed once a second, which the `ticks`
column shows. So these rows cannot drive the running average tick by tick.
What they are good for is the pairs that sit on one line together, above all
the average and the gain that average asked for, and the range of readings the
guards have to cope with.
"""
import os
import re
import sys

FIELDS = ("freq", "sig", "mod", "ticks")

# A column the capture did not have. Writing 0 instead would put a real
# looking answer in a field that means "the gain the average asked for", and
# the first capture has no such column at all.
MISSING = -128
OPTIONAL = ("on", "usn", "want", "gain", "avg")


def rows(path):
    """Every printed sample in one capture.

    `avg` is the only field with a decimal point, and it is kept in tenths so
    the header holds whole numbers. Everything else is checked to be a whole
    number rather than matched loosely, because a capture misread by a factor
    of ten would take every threshold fitted to it with it.
    """
    for number, line in enumerate(open(path), start=1):
        if not line.strip():
            continue
        found = dict(re.findall(r"(\w+)=(-?[\d.]+)", line))
        if "mod" not in found:
            continue
        row = {}
        for field in FIELDS + OPTIONAL:
            if field not in found:
                row[field] = None
                continue
            text = found[field]
            if field == "avg":
                if not re.fullmatch(r"-?\d+(\.\d+)?", text):
                    raise SystemExit("%s line %d: avg=%s is not a number"
                                     % (path, number, text))
                row[field] = int(round(float(text) * 10))
                continue
            if not re.fullmatch(r"-?\d+", text):
                raise SystemExit("%s line %d: %s=%s is not a whole number"
                                 % (path, number, field, text))
            row[field] = int(text)
        yield row


# Where the AGC's noise limit was measured from, and which of its frequencies
# were transmitting. Kept here rather than in the test so that retaking the
# capture and rerunning this is all it takes.
SQUELCH_CAPTURE = "test/fixtures/squelch/shoulder-2026-09-13.log"
SQUELCH_STATIONS = (91100, 92700, 98300, 101900, 102800, 106400)


def station_noise(path):
    """The ultrasonic noise on every station reading in the squelch capture."""
    out = []
    for line in open(path):
        found = dict(re.findall(r"(\w+)=(-?\d+)", line))
        if "khz" not in found or "usn" not in found:
            continue
        if int(found["khz"]) in SQUELCH_STATIONS:
            out.append(int(found["usn"]))
    return out


def main():
    target = sys.argv[1]
    sources = sys.argv[2:]
    out = [
        "/**",
        " * @file %s" % os.path.basename(target),
        " * @brief AGC readings taken off the radio, for the AGC tests.",
        " *",
        " * Generated by tools/make_agc.py. Do not edit. See",
        " * test/fixtures/agc/README.md for what these are, how they were",
        " * taken and what each one shows.",
        " *",
        " * One row is one printed sample, which is up to ten AGC updates, so",
        " * these cannot drive the running average one row at a time. The",
        " * average and the gain it asked for sit on the same row, and that",
        " * pairing is what the tests check.",
        " */",
        "#ifndef TEST_AGC_CAPTURES_H",
        "#define TEST_AGC_CAPTURES_H",
        "",
        "#include <stdint.h>",
        "",
        "/** One printed sample from the prototype that produced the captures. */",
        "typedef struct {",
        "  uint8_t file;          /**< Which capture, 1 to 5. */",
        "  uint16_t freq;         /**< Frequency in units of 10 kHz. */",
        "  uint8_t target;        /**< The AGC target in modulation percent. */",
        "  int16_t levelDbuV;     /**< Signal level in whole dBuV. */",
        "  int16_t noiseTenths;   /**< Ultrasonic noise, or -1 if not logged. */",
        "  int16_t modPercent;    /**< Modulation depth as the chip reported it. */",
        "  int16_t averageTenths; /**< The prototype's running average, tenths. */",
        "  int16_t ticks;         /**< Usable updates behind that average. */",
        "  int16_t wantedDb;      /**< The gain that average asked for. */",
        "  int16_t gainDb;        /**< The gain actually applied. */",
        "  /* -128 in either of those two means the capture had no such",
        "   * column. The first capture predates them. */",
        "} AgcRow;",
        "",
        "static const AgcRow kAgcCapture[] = {",
    ]
    # Both taken from the file name of the last capture rather than written
    # here, so retaking it at a different boost cannot leave the test checking
    # 168 rows against a ceiling they were never recorded at.
    final = sorted(sources)[-1]
    final_file = len(sources)
    match = re.search(r"boost(\d+)", os.path.basename(final))
    if match is None:
        raise SystemExit("%s: no boost in the file name, so the boost the "
                         "capture was taken at cannot be known" % final)
    final_boost = int(match.group(1))

    count = 0
    for index, source in enumerate(sorted(sources), start=1):
        for row in rows(source):
            target_percent = row["on"]
            # The first capture logged on= as a flag, 1 for running, rather
            # than as the target. Every one of its lines was taken at a target
            # of 50, which is what its file name says. A later capture logs
            # on=0 to mean the AGC was switched off for those lines, and that
            # is a real 0 rather than a flag, so the two are told apart rather
            # than lumped together.
            if target_percent is None:
                target_percent = 50
            elif target_percent == 1:
                target_percent = 50
            out.append(
                "    {%d, %d, %d, %d, %d, %d, %d, %d, %d, %d}," %
                (index, row["freq"] or 0, target_percent, row["sig"] or 0,
                 -1 if row["usn"] is None else row["usn"], row["mod"],
                 row["avg"] if row["avg"] is not None else 0,
                 row["ticks"] if row["ticks"] is not None else -1,
                 row["want"] if row["want"] is not None else MISSING,
                 row["gain"] if row["gain"] is not None else MISSING))
            count += 1
    noise = station_noise(SQUELCH_CAPTURE)
    out += [
        "};",
        "",
        "/**",
        " * The noise on every station reading in the squelch capture.",
        " *",
        " * Where AGC_MAX_NOISE_TENTHS comes from. Generated from",
        " * %s" % SQUELCH_CAPTURE,
        " * so that retaking that capture and rerunning the generator is all",
        " * it takes for the test to be checking the new numbers.",
        " */",
        "static const int16_t kStationNoiseTenths[] = {",
        "    " + ", ".join(str(v) for v in noise) + "};",
        "",
        "/** How many station readings that is. */",
        "#define AGC_STATION_NOISE_COUNT %d" % len(noise),
        "",
        "/** How many printed samples there are across every capture. */",
        "#define AGC_CAPTURE_COUNT %d" % count,
        "",
        "/** The capture the final tuning was measured from. */",
        "#define AGC_FINAL_FILE %d" % final_file,
        "",
        "/** The boost that capture was taken with, in dB. */",
        "#define AGC_FINAL_BOOST %d" % final_boost,
        "",
        "#endif /* TEST_AGC_CAPTURES_H */",
        "",
    ]
    open(target, "w").write("\n".join(out))
    print("%d samples written to %s" % (count, target))


main()
