"""Turn a band sweep log into a header the native tests can replay.

The tests have to run anywhere, including on the CI machine, so they cannot
open a file out of the working directory. Generating a header keeps the test
hermetic and keeps the real readings as the thing being tested, which is the
whole point of taking them.

    python3 tools/make_sweep.py test/fixtures/seek/fm-sweep-2026-09-13.log \
        test/test_seek/fm_sweep.h

Same idea as tools/make_font.py. Rerun it when a sweep is added or retaken,
and commit the result.
"""
import re
import sys

FIELDS = ("khz", "sig", "usn", "wam", "offset", "mod", "snr")


def rows(path):
    for line in open(path):
        found = dict(re.findall(r"(\w+)=(-?\w+)", line))
        if "khz" not in found:
            continue
        row = {k: int(found[k]) for k in FIELDS if k in found}
        row["st"] = found.get("st") == "True"
        yield row


def main():
    source, target = sys.argv[1], sys.argv[2]
    out = [
        "/**",
        " * @file %s" % target.rsplit("/", 1)[-1],
        " * @brief A band sweep taken off the radio, for the seek tests.",
        " *",
        " * Generated by tools/make_sweep.py from",
        " * %s" % source,
        " * Do not edit. See test/fixtures/seek/README.md for what it is and",
        " * how it was taken.",
        " */",
        "#ifndef TEST_FM_SWEEP_H",
        "#define TEST_FM_SWEEP_H",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "/** One channel, as the radio read it. */",
        "typedef struct {",
        "  uint32_t khz;      /**< The frequency that was tuned. */",
        "  int16_t levelTenths;   /**< Signal level, tenths of a dBuV. */",
        "  uint16_t noiseTenths;  /**< Ultrasonic noise. */",
        "  uint16_t multipathTenths; /**< Multipath. */",
        "  int16_t offsetTenths;  /**< How far off centre, tenths of a kHz. */",
        "  bool stereo;       /**< The chip saw a stereo pilot. */",
        "} SweepRow;",
        "",
        "static const SweepRow kFmSweep[] = {",
    ]
    count = 0
    for row in rows(source):
        out.append(
            "    {%d, %d, %d, %d, %d, %s},"
            % (row["khz"], row["sig"], row["usn"], row["wam"], row["offset"],
               "true" if row["st"] else "false"))
        count += 1
    out += [
        "};",
        "",
        "/** How many channels the sweep covers. */",
        "#define FM_SWEEP_COUNT %d" % count,
        "",
        "/**",
        " * The stations that were actually transmitting when it was taken.",
        " *",
        " * Confirmed by ear and by the stereo flag. Four frequencies on the",
        " * known station list in docs/test-checklist.md were off air that",
        " * afternoon and read as noise here, which is what they were.",
        " */",
        "static const uint32_t kFmSweepStations[] = {93500,  95000,  98300,",
        "                                           101900, 104000, 106400};",
        "",
        "/** How many of them there were. */",
        "#define FM_SWEEP_STATION_COUNT 6",
        "",
        "#endif /* TEST_FM_SWEEP_H */",
        "",
    ]
    open(target, "w").write("\n".join(out))
    print("%s: %d channels" % (target, count))


main()
