"""Turn a squelch capture into a header the native tests can replay.

The tests have to run anywhere, including on the CI machine, so they cannot
open a file out of the working directory. Generating a header keeps the test
hermetic and keeps the real readings as the thing being tested, which is the
whole point of taking them.

    python3 tools/make_squelch.py test/fixtures/squelch/shoulder-2026-09-13.log \
        test/test_squelch/shoulder.h

Same idea as tools/make_sweep.py. Rerun it when a capture is added or retaken,
run clang-format over the result, and commit it. The format gate covers
generated headers like any other, so a header straight out of here fails it.
"""
import re
import sys

FIELDS = ("khz", "sig", "sav", "usn", "wam", "offset")


def rows(path):
    """Every reading in the log, as whole numbers.

    Every field is checked rather than pattern matched loosely. A capture
    written with a decimal point would otherwise be read as the part before
    the dot, silently out by a factor of ten, which is the kind of quiet
    wrongness a threshold fitted to it would inherit.
    """
    for number, line in enumerate(open(path), start=1):
        if not line.strip():
            continue
        found = dict(re.findall(r"(\w+)=(\S+)", line))
        if "khz" not in found:
            continue
        row = {}
        for field in FIELDS:
            if field not in found:
                raise SystemExit("%s line %d: no %s in %r"
                                 % (path, number, field, line.strip()))
            text = found[field]
            if not re.fullmatch(r"-?\d+", text):
                raise SystemExit("%s line %d: %s=%s is not a whole number"
                                 % (path, number, field, text))
            row[field] = int(text)
        yield row


def main():
    source, target = sys.argv[1], sys.argv[2]
    out = [
        "/**",
        " * @file %s" % target.rsplit("/", 1)[-1],
        " * @brief Squelch readings taken off the radio, for the squelch tests.",
        " *",
        " * Generated by tools/make_squelch.py from",
        " * %s" % source,
        " * Do not edit. See test/fixtures/squelch/README.md for what it is,",
        " * how it was taken and what it shows.",
        " */",
        "#ifndef TEST_SHOULDER_H",
        "#define TEST_SHOULDER_H",
        "",
        "#include <stdint.h>",
        "",
        "/** One reading, as the radio took it. */",
        "typedef struct {",
        "  uint32_t khz;             /**< The frequency that was tuned. */",
        "  int16_t levelTenths;      /**< Signal level, tenths of a dBuV. */",
        "  /**",
        "   * The same level as the radio itself smoothed it, tenths of a dBuV.",
        "   *",
        "   * Captured rather than worked out here, because the smoothing is per",
        "   * reading and the radio takes ten a second while this capture took",
        "   * about three. Replaying the raw column through the average gives a",
        "   * far heavier smoothing than the radio applies, so the level floor",
        "   * is judged against this column and not against a replay.",
        "   */",
        "  int16_t smoothedTenths;",
        "  uint16_t noiseTenths;     /**< Ultrasonic noise. */",
        "  uint16_t multipathTenths; /**< Multipath. */",
        "  int16_t offsetTenths;     /**< How far off centre, tenths of a kHz. */",
        "} ShoulderRow;",
        "",
        "static const ShoulderRow kShoulderCapture[] = {",
    ]
    count = 0
    for row in rows(source):
        out.append("    {%d, %d, %d, %d, %d, %d}," %
                   (row["khz"], row["sig"], row["sav"], row["usn"], row["wam"],
                    row["offset"]))
        count += 1
    out += [
        "};",
        "",
        "/** How many readings the capture holds. */",
        "#define SHOULDER_COUNT %d" % count,
        "",
        "/** The shoulder of 101.9, which the auto squelch used to sit open on. */",
        "#define SHOULDER_KHZ 102000",
        "",
        "/** The weakest station that was on air, which it must never mute. */",
        "#define SHOULDER_WEAKEST_STATION_KHZ 92700",
        "",
        "/** A channel with nothing on it at all. */",
        "#define SHOULDER_EMPTY_KHZ 105000",
        "",
        "#endif /* TEST_SHOULDER_H */",
        "",
    ]
    open(target, "w").write("\n".join(out))
    print("%d readings written to %s" % (count, target))


main()
