#!/usr/bin/env python3
"""Vendor Pico CSS and htmx into the firmware image.

The web pages have to work with no internet, only LAN, so the CSS and JS
libraries they use cannot be loaded from a CDN the way a page on the open web
would. This script downloads each one, pinned to an exact version, gzips it, and
writes the result into src/net/web_assets.h as a byte array. web_update.cpp
serves that array straight over the wire with a gzip Content-Encoding header, so
the radio pays the compressed size once, in flash, and never decompresses it
itself.

Pinned versions, and the licence each is under:

    Pico CSS    2.1.1  MIT               https://picocss.com
    htmx        2.0.10 Zero-Clause BSD   https://htmx.org

    python3 tools/vendor_web_assets.py

Rerun it only to move to a newer pinned version, then run clang-format over
the result and commit the header. The format gate covers a generated file
like any other.
"""

import gzip
import urllib.request

ASSETS = [
    (
        "picoCss",
        "https://cdn.jsdelivr.net/npm/@picocss/pico@2.1.1/css/pico.min.css",
        "MIT",
    ),
    (
        "htmxJs",
        "https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js",
        "Zero-Clause BSD",
    ),
]


def emit_array(name, data):
    rows = []
    for i in range(0, len(data), 20):
        rows.append(",".join(str(b) for b in data[i : i + 20]))
    body = ",\n    ".join(rows)
    symbol = name[0].upper() + name[1:]
    return (
        f"static const uint8_t k{symbol}Gz[] PROGMEM = {{\n    {body}}};\n"
        f"static const size_t k{symbol}GzLen = sizeof(k{symbol}Gz);\n"
    )


def main():
    out = [
        "#pragma once",
        "",
        "/* Generated by tools/vendor_web_assets.py. Do not hand edit. */",
        "",
        "#include <Arduino.h>",
        "",
    ]
    for name, url, licence in ASSETS:
        print("fetching", url)
        with urllib.request.urlopen(url, timeout=20) as response:
            raw = response.read()
        compressed = gzip.compress(raw, compresslevel=9, mtime=0)
        print(f"  {len(raw)} bytes, {len(compressed)} gzipped")
        out.append(f"/* {url}\n * Licence: {licence}. */")
        out.append(emit_array(name, compressed))
    with open("src/net/web_assets.h", "w") as f:
        f.write("\n".join(out))
    print("wrote src/net/web_assets.h")


if __name__ == "__main__":
    main()
